### PR TITLE
Makefile & Vagrantfile

### PR DESCRIPTION
**Pull request by iankronquist**

### CODE REVIEW

**Comment by iankronquist** [comment]
Fixes #3.

**Comment by iankronquist** [comment]
This still works but I'm closing it so I don't have extraneous open prs.

**Comment by iankronquist** [comment]
Resolved merge conflicts.

**Comment by s-mcf** [comment]
I'll have to take a more careful look at this and try to remember how I actually build and boot this thing.

**Comment by iankronquist** [comment]
`make && make start` should do the trick. Also consult your `build.sh`.

**Pull request closed without merging**
